variable "rgs" {}
variable "stgs" {}
variable "vnets" {}
variable "subnets" {}
variable "network_interfaces" {}
variable "pips" {}
variable "vms" {}
variable "nsgs" {}
variable "subnet_nsg_associations" {}